"""
Service for detecting AI-generated content using a two-layer approach:
1. Transformer model (roberta-base-openai-detector)
2. Statistical heuristics (Burstiness, Bigram entropy, Type-Token Ratio)
"""

import math
import re
import logging
from typing import Tuple
from collections import Counter
from transformers import pipeline

logger = logging.getLogger(__name__)

_classifier = None

def _clamp(val: float, min_val: float, max_val: float) -> float:
    return max(min_val, min(val, max_val))

def check_ai_content(report_text: str) -> Tuple[float, str]:
    """
    Analyzes text to detect if it was generated by AI.
    
    Args:
        report_text: The student's submitted text.
        
    Returns:
        A tuple of (final_score, details_message).
    """
    global _classifier
    
    # Lazy load transformer model on first request
    from transformers import pipeline
    if _classifier is None:
        try:
            _classifier = pipeline(
                "text-classification",
                model="openai-community/roberta-base-openai-detector",
                truncation=True,
                max_length=512
            )
        except Exception as e:
            logger.error(f"Failed to load AI detector model: {e}")
            _classifier = "failed"
            
    transformer_score = -1.0
    if _classifier != "failed":
        try:
            # Only pass first chunk if report is extremely long
            result = _classifier(report_text[:2000])[0]
            label = result["label"]
            score = result["score"]
            if label == "Fake":
                transformer_score = score
            else:
                transformer_score = 1.0 - score
        except Exception as e:
            logger.error(f"Error running transformer inference: {e}")
            transformer_score = -1.0
            
    # Heuristics Layer
    text_lower = report_text.lower()
    
    # A. Burstiness score
    sentences = re.split(r'[.!?]', text_lower)
    lengths = []
    for s in sentences:
        words_in_s = s.split()
        if len(words_in_s) >= 3:
            lengths.append(len(words_in_s))
            
    if lengths:
        mean_len = sum(lengths) / len(lengths)
        variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        std = math.sqrt(variance)
        ratio = std / mean_len if mean_len > 0 else 0.0
        burstiness_score = _clamp(1.0 - (ratio - 0.3) / 0.5, 0.0, 1.0)
    else:
        burstiness_score = 0.5
        
    # B. Bigram entropy score
    words = re.findall(r'[a-z]+', text_lower)
    if len(words) > 1:
        bigrams = list(zip(words[:-1], words[1:]))
        bigram_counts = Counter(bigrams)
        total_bigrams = len(bigrams)
        entropy = 0.0
        for count in bigram_counts.values():
            p = count / total_bigrams
            entropy -= p * math.log2(p)
        entropy_score = _clamp(1.0 - (entropy - 4.0) / 8.0, 0.0, 1.0)
    else:
        entropy_score = 0.5
        
    # C. Type-Token Ratio (TTR) score
    if words:
        unique_words = set(words)
        ttr = len(unique_words) / len(words)
        if 0.42 <= ttr <= 0.62:
            centre = 0.52
            distance = abs(ttr - centre)
            ttr_score = _clamp(0.85 - distance * 3.5, 0.5, 0.85)
        else:
            ttr_score = 0.25
    else:
        ttr_score = 0.5
        
    # Combined heuristic score
    heuristic_score = 0.45 * entropy_score + 0.35 * burstiness_score + 0.20 * ttr_score
    
    # Final combined score
    if transformer_score >= 0.0:
        final_score = 0.65 * transformer_score + 0.35 * heuristic_score
    else:
        final_score = heuristic_score
        
    details = (
        f"Transformer: {transformer_score:.2f}, "
        f"Burstiness: {burstiness_score:.2f}, "
        f"Entropy: {entropy_score:.2f}, "
        f"TTR: {ttr_score:.2f}"
    )
    
    return final_score, details
